Backup arweave wallet
ardriveapp/ardrive-desktop pull request #73
Opened 2021-03-17 21:10 UTC by ykatyhoney

http://redmine.ardrive.io/issues/161

Please review it.

2021-03-23 22:33 UTC, agsuy requested changes
After switching to this branch and building the app I got a white empty screen. 
This will be rejected until we are able to test this feature.
Rejected.

2021-03-26 05:17 UTC, ykatyhoney commented
@agsuy The issues are solved. you can try to review this branch again.

2021-03-29 00:26 UTC, agsuy approved these changes

2021-03-29 00:33 UTC, agsuy commented
There is an issue in the /packages/renderer/src/app/redux/sagas/auth.ts line 27 that we will be patching in another PR.

Merging

2021-03-29 00:33 UTC, merged